apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: dapr
spec:
  clusterSelector:
    matchLabels:
      type: aws
  serviceSpec:
    services:
      - template: ingress-nginx-4-11-3
        name: ingress-nginx
        namespace: ingress-nginx
        values: |
          ingress-nginx:
            controller:
              hostPort:
                enabled: true
      - template: dapr-1-14-4
        name: dapr
        namespace: dapr
      - template: dapr-dashboard-0-15-0
        name: dapr-dashboard
        namespace: dapr
        values: |
          ingress:
            enabled: true
            className: nginx
            host: 'dapr.example.com'
